 # --- CI-tools images versions ---
include:
  - local: "ci-tools-versions.yml"

cache:
  key: terraform-plugins
  paths:
    - ${TF_ROOT}/.terraform.d/plugin-cache/

stages:
  - Lints & Checks
  - Terraform plan
  - Infrastructure Provision
  - K8s Setup
  - Deploy CNI to Cluster

variables:
  # --- Full image paths ---
  TF_IMAGE: "${REGISTRY_PATH}/tf-runner:40004d34"
  ANSIBLE_IMAGE: "${REGISTRY_PATH}/ansible-runner:f649be37"
  K8S_IMAGE: "${REGISTRY_PATH}/k8s-deployer:55ee5249"

  # --- Settings ---
  TF_ROOT: "${CI_PROJECT_DIR}/terraform"
  ANSIBLE_ROOT: "${CI_PROJECT_DIR}/ansible"
  PACKER_ROOT: "${CI_PROJECT_DIR}/packer"

  TF_PLUGIN_CACHE_DIR: "${TF_ROOT}/.terraform.d/plugin-cache"
  TF_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/production"
  TF_HTTP_USERNAME: "gitlab-ci-token"
  TF_HTTP_PASSWORD: "${CI_JOB_TOKEN}"
  TF_VAR_ssh_key: "${PUBLIC_SSH_KEY_PATH}"

  ANSIBLE_CONFIG: "${ANSIBLE_ROOT}/ansible.cfg"
  ANSIBLE_HOST_KEY_CHECKING: "False"

# --- Validation Jobs ---

.tf_lint_template:
  stage: Lints & Checks
  image:
    name: ${TF_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner

.ansible_lint_template:
  stage: Lints & Checks
  image:
    name: ${ANSIBLE_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner

terraform_validate:
  extends: [.tf_lint_template]
  script:
    - cd "${TF_ROOT}"
    - terraform init -backend=false
    - terraform fmt -check -recursive
    - terraform validate

terraform_tflint:
  extends: [.tf_lint_template]
  script:
    - cd "${TF_ROOT}"
    - tflint --init
    - tflint --recursive

terraform_tfsec:
  extends: [.tf_lint_template]
  script:
    - tfsec "${TF_ROOT}"

ansible_yamllint:
  extends: [.ansible_lint_template]
  script:
    - yamllint "${ANSIBLE_ROOT}"

ansible_lint:
  extends: [.ansible_lint_template]
  before_script:
    - cd "${ANSIBLE_ROOT}"
  script:
    - ansible-lint

terraform_plan:
  stage: Terraform plan
  image:
    name: ${TF_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner
  script:
    - cd "${TF_ROOT}"
    - >
      terraform init
      -backend-config="address=${TF_ADDRESS}"
      -backend-config="lock_address=${TF_ADDRESS}/lock"
      -backend-config="unlock_address=${TF_ADDRESS}/lock"
      -backend-config="lock_method=POST"
      -backend-config="unlock_method=DELETE"
      -backend-config="retry_wait_min=5"
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - "${TF_ROOT}/tfplan"

terraform_apply:
  stage: Infrastructure Provision
  image:
    name: ${TF_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner
  script:
    - cd "${TF_ROOT}"
    - >
      terraform init
      -backend-config="address=${TF_ADDRESS}"
      -backend-config="lock_address=${TF_ADDRESS}/lock"
      -backend-config="unlock_address=${TF_ADDRESS}/lock"
      -backend-config="lock_method=POST"
      -backend-config="unlock_method=DELETE"
      -backend-config="retry_wait_min=5"
    - terraform apply -auto-approve "tfplan"
    - terraform output -json ansible_inventory > ${ANSIBLE_ROOT}/inventory.json
    - cat ${ANSIBLE_ROOT}/inventory.json
  rules:    
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  allow_failure: false  
  dependencies:
    - terraform_plan
  artifacts:
    paths:
      - "${ANSIBLE_ROOT}/inventory.json"

configure_k8s:
  stage: K8s Setup
  image: 
    name: ${ANSIBLE_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner
  needs:
    - job: terraform_apply 
      artifacts: true
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - mkdir -p ~/.kube
  script:
    - cd "${ANSIBLE_ROOT}"
    - jq -r '.. | .ansible_host? // empty' inventory.json | xargs ssh-keyscan -H >> $HOME/.ssh/known_hosts
    - ansible-playbook -i inventory.json configure-nodes.yml
    - export cluster_external_vip=$(grep '^cluster_external_vip:' "$ANSIBLE_ROOT/group_vars/all.yml" | awk '{print $2}' | tr -d '"')
    - 'sed -i "s|server: https://.*:6443|server: https://${cluster_external_vip}:6443|g" k8s_admin.conf'
    - cp k8s_admin.conf $HOME/.kube/config
    - chmod 600 $HOME/.kube/config
  rules:    
    - if: $CI_COMMIT_BRANCH == "main"
  artifacts:
    paths:
      - "${ANSIBLE_ROOT}/k8s_admin.conf"
    expire_in: 1 day

configure_network:
  stage: Deploy CNI to Cluster
  image: 
    name: ${K8S_IMAGE}
    entrypoint: [""]
  needs:
    - job: configure_k8s
      artifacts: true
  script:
    - mkdir -p $HOME/.kube
    - cp "${ANSIBLE_ROOT}/k8s_admin.conf" $HOME/.kube/config
    - chmod 600 $HOME/.kube/config
    - kubectl cluster-info
    - cd "${ANSIBLE_ROOT}"
    - ansible-playbook configure-network.yml
  rules:    
    - if: $CI_COMMIT_BRANCH == "main"
  

