 # --- CI-tools images versions ---
include:
  - local: "ci-tools-versions.yml"

cache:
  key: terraform-plugins
  paths:
    - ${TF_ROOT}/.terraform.d/plugin-cache/

stages:
  - Lints & Checks
  - Bake Image
  - Infrastructure Provision
  - K8s Setup

variables:
  # --- Full image paths ---
  TF_IMAGE: "hashicorp/terraform:1.7.5"
  ANSIBLE_IMAGE: "${REGISTRY_PATH}/ansible-runner:aa7736bc"
  K8S_IMAGE: "${REGISTRY_PATH}/k8s-deployer:${K8S_DEPLOYER_VER}"
  PACKER_IMAGE: "winterlyembrace/k8s-packer:latest"

  # --- Settings ---
  TF_ROOT: "${CI_PROJECT_DIR}/terraform"
  ANSIBLE_ROOT: "${CI_PROJECT_DIR}/ansible"
  PACKER_ROOT: "${CI_PROJECT_DIR}/packer"

  TF_PLUGIN_CACHE_DIR: "${TF_ROOT}/.terraform.d/plugin-cache"
  TF_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/production"
  TF_HTTP_USERNAME: "gitlab-ci-token"
  TF_HTTP_PASSWORD: "${CI_JOB_TOKEN}"
  TF_VAR_ssh_key: "${PUBLIC_SSH_KEY_PATH}"

  ANSIBLE_CONFIG: "${ANSIBLE_ROOT}/ansible.cfg"
  ANSIBLE_HOST_KEY_CHECKING: "False"

# --- Validation Jobs ---

#terraform_validate:
#  stage: Lints & Checks
#  image:
#    name: ${TF_IMAGE}
#    entrypoint: [""]
#  tags:
#    - cluster-runner
#  script:
#    - cd "${TF_ROOT}"
#    - terraform init -backend=false
#    - terraform fmt -check -recursive
#    - terraform validate

#terraform_tflint:
#  stage: Lints & Checks
#  image:
#    name: ${TF_IMAGE}
#    entrypoint: [""]
#  tags:
#    - cluster-runner
#  script:
#    - cd "${TF_ROOT}"
#    - tflint --init
#    - tflint --recursive

#terraform_tfsec:
#  stage: Lints & Checks
#  image:
#    name: ${TF_IMAGE}
#    entrypoint: [""]
#  tags:
#    - cluster-runner
#  script:
#    - tfsec "${TF_ROOT}"

#ansible_yamllint:
#  stage: Lints & Checks
#  image:
#    name: ${ANSIBLE_IMAGE}
#    entrypoint: [""]
#  tags:
#    - cluster-runner
# script:
#    - yamllint "${ANSIBLE_ROOT}"

#ansible_lint:
#  stage: Lints & Checks
#  image: 
#    name: ${ANSIBLE_IMAGE}
#    entrypoint: [""]
#  tags:
#    - cluster-runner
#  before_script:
#    - cd "${ANSIBLE_ROOT}"
#  script:
#    - ansible-lint

packer_build:
  stage: Bake Image
  image: 
    name: ${PACKER_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner
  script:
    - cd "${PACKER_ROOT}"
    - packer init .
    - packer build -force .
  rules:
    - changes:
        - packer/**/*
      when: on_success

terraform_plan:
  stage: Infrastructure Provision
  image:
    name: ${TF_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner
  script:
    - cd "${TF_ROOT}"
    - >
      terraform init
      -backend-config="address=${TF_ADDRESS}"
      -backend-config="lock_address=${TF_ADDRESS}/lock"
      -backend-config="unlock_address=${TF_ADDRESS}/lock"
      -backend-config="lock_method=POST"
      -backend-config="unlock_method=DELETE"
      -backend-config="retry_wait_min=5"
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 1 hour

terraform_apply:
  stage: Infrastructure Provision
  image:
    name: ${TF_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner
  before_script:
    - apk add --no-cache cdrkit
  script:
    - cd "${TF_ROOT}"
    - >
      terraform init
      -backend-config="address=${TF_ADDRESS}"
      -backend-config="lock_address=${TF_ADDRESS}/lock"
      -backend-config="unlock_address=${TF_ADDRESS}/lock"
      -backend-config="lock_method=POST"
      -backend-config="unlock_method=DELETE"
      -backend-config="retry_wait_min=5"
    - ls -la
    - terraform apply -auto-approve tfplan
    - terraform output -json ansible_inventory > ${ANSIBLE_ROOT}/inventory.json
    - cat ${ANSIBLE_ROOT}/inventory.json
  rules:    
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  allow_failure: false  
  dependencies:
    - terraform_plan
  artifacts:
    paths:
      - ${ANSIBLE_ROOT}/inventory.json

configure_k8s:
  stage: K8s Setup
  image: 
    name: ${ANSIBLE_IMAGE}
    entrypoint: [""]
  tags:
    - cluster-runner
  needs:
    - job: terraform_apply 
      artifacts: true
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - cd "${ANSIBLE_ROOT}"
    - ansible-playbook -i inventory.json playbook-configure-nodes.yml
  rules:    
    - if: $CI_COMMIT_BRANCH == "main"
