- name: Generate join facts
  when: inventory_hostname == groups['masters'][0]
  block:
    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: worker_join_raw
      changed_when: false

    - name: Get certificate key
      ansible.builtin.shell: |
        set -o pipefail
        kubeadm init phase upload-certs --upload-certs | tail -n 1
      args:
        executable: /bin/bash
      register: cert_key_raw
      changed_when: false

    - name: Share join facts with all hosts
      ansible.builtin.set_fact:
        master_join_cmd: "{{ worker_join_raw.stdout }} --control-plane --certificate-key {{ cert_key_raw.stdout }} --apiserver-bind-port {{ k8s_apiserver_bind_port }}"
        worker_join_cmd_fact: "{{ worker_join_raw.stdout }}"
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['all'] }}"

- name: Join other masters
  ansible.builtin.command: >
    {{ master_join_cmd }}
    --node-name {{ inventory_hostname }}
    --apiserver-advertise-address={{ internal_ip }}
  when:
    - inventory_hostname in groups['masters']
    - inventory_hostname != groups['masters'][0]
  args:
    creates: /etc/kubernetes/kubelet.conf