---
- name: Reset kubeadm
  ansible.builtin.command: kubeadm reset -f
  register: reset_k8s_reset_out
  changed_when: true

- name: Remove Kubernetes config and data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes/
    - /var/lib/etcd/
    - /var/lib/kubelet/
    - /var/lib/cni/
    - /etc/cni/net.d/
    - "/home/{{ ansible_user }}/.kube/"
