---
- name: Apply Calico manifest directly from GitHub
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/winterlyembrace/k8s-gitops-config/refs/heads/main/calico/calico.yaml"
  delegate_to: localhost

- name: Install Argo CD via Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    values:
      server:
        service:
          type: NodePort
