---
- name: Apply Calico manifest directly from GitHub
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/winterlyembrace/k8s-gitops-config/refs/heads/main/calico/calico.yaml"
  delegate_to: localhost

- name: Wait for all nodes to be Ready (Calico initialization)
  ansible.builtin.command:
    cmd: "kubectl wait --for=condition=Ready nodes --all --timeout=300s"
  delegate_to: localhost
  changed_when: false

- name: Add Argo CD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "https://argoproj.github.io/argo-charts"

- name: Install Argo CD via Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    values:
      server:
        service:
          type: NodePort
