---
- name: Check if node is already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_worker_kubelet_conf

- name: Join worker node to the cluster
  ansible.builtin.command: >
    {{ hostvars[groups['masters'][0]]['k8s_master_worker_join_cmd_fact'] }}
    --node-name {{ inventory_hostname }}
    --apiserver-advertise-address={{ cluster_internal_vip }}
  when: not k8s_worker_kubelet_conf.stat.exists
  register: k8s_worker_join
  changed_when: k8s_worker_join.rc == 0
  args:
    creates: /etc/kubernetes/kubelet.conf

- name: Label worker nodes for Cilium L2 Announcement
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ inventory_hostname }}"
        labels:
          node-role.com/type: worker
