---
- name: Configure Master Nodes
  hosts: masters
  become: true
  roles:
    - deploy_ha
    - k8s_master

- name: Configure Worker Nodes
  hosts: workers
  become: true
  roles:
    - k8s_worker

