---
- name: "Initial setup of k8s nodes"
  hosts: web_servers
  become: yes
  tasks:
    - name: "Wait for system to become reachable"
      wait_for_connection:
        timeout: 60

    - name: "Update apt cache"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Check Docker version"
      command: docker --version
      register: docker_check
      ignore_errors: yes

    - name: "Show Docker version"
      debug:
        msg: "Docker is installed: {{ docker_check.stdout }}"
