---
- name: Pre-pull Kubernetes images for fast init
  ansible.builtin.command:
    cmd: kubeadm config images pull --kubernetes-version v1.29.15
  changed_when: true

- name: Initialize first master
  ansible.builtin.command: >
    kubeadm init
    --control-plane-endpoint "{{ cluster_internal_vip }}:6443"
    --apiserver-cert-extra-sans="{{ cluster_internal_vip }},{{ cluster_external_vip }},127.0.0.1,{{ inventory_hostname }}"
    --upload-certs
    --apiserver-advertise-address={{ internal_ip }}
    --apiserver-bind-port {{ k8s_apiserver_bind_port }}
    --pod-network-cidr={{ pod_network_cidr }}
    --node-name {{ inventory_hostname }}
  register: kubeadm_init_raw
  when: inventory_hostname == groups['masters'][0]
  args:
    creates: /etc/kubernetes/admin.conf

- name: Setup kubeconfig and fetch to local machine
  block:
    - name: Create .kube directory for root
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Copy admin.conf to local kubeconfig
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Fetch kubeconfig to local machine
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "./k8s_admin.conf"
        flat: true
      when: inventory_hostname == groups['masters'][0]
